### PR TITLE
Fix infinite loop with mismatched begin/end tags

### PR DESCRIPTION
**Pull request by gnuish**
It is caused from the `self.pos = begin.pos;` right before the tags error is returned in `consume_component()`, causing the recursion to start from the beginning over and over.

As of right now, that `begin.pos` is useless because the public API just uses `parse_component()` (which creates a new Parser that's never re-used) and `consume_component()` is private, even though `consume_property()` is public.

Other changes in this PR are line folding (benched 10x faster on my machine and doesn't mess Unicode chars), and minor cleanups.

If anything needs changing let me know ✌️

### CODE REVIEW

**Comment by gnuish** [comment]
Removed commits that change the public API

**Comment by untitaker** [comment]
There's way more happing here than the bugfix in the title. Could you split that up?

**Comment by gnuish** [comment]
Done

**Comment by untitaker** [comment]
I chose a different way, as I want every `consume` function to roll back if parsing fails. Thanks though!

**Pull request closed without merging**
