### PR TITLE
Use newer versions of rustc in CI

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Updates the rustc versions used in CI.

If you want to keep 1.19 (for example) to ensure compatibility, I'll re-add it!

### CODE REVIEW

**Comment by untitaker** [comment]
I'd like to keep all previously existing rust versions as well. I'm not committing to supporting them indefinitely but I'd like to drop support to them at least consciously, not accidentally.

**Comment by untitaker** [comment]
That said I don't think it makes sense to keep both `1.22.0` and `1.22.1`

**Comment by matthiasbeyer** [comment]
The CI error seems not to be our fold, could you please re-trigger this?

**Comment by untitaker** [comment]
It is the fault of this PR, there is no such download for whatever reason. Will fix on master directly

**Pull request closed without merging**
