### PR TITLE
Update dependency: error-chain

### PR DESCRIPTION
**Pull request by matthiasbeyer**
As this is a breaking change, we would need to release a new minor version of rust-vobject for this.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Here we go.

**Comment by untitaker** [comment]
Can we not use `failure::Error`? I am not sure what we have but it should be possible to wrap the few external errors in enum variants.

Thanks for your work btw!

**Comment by untitaker** [comment]
(reason for this is that it's hard to get a concrete enum variant out of a `Error` back. There's a cost with this that the user shouldn't have to pay)

**Comment by matthiasbeyer** [comment]
Hmm I can try. Funny is that it compiles for my device at home, but not on travis

**Comment by untitaker** [comment]
Check with `cargo test`, the crate compiles but the tests dont

**Comment by matthiasbeyer** [comment]
Hhm it is a bit complicated actually... Why wouldn't `failure::Error::downcast()` work in your opinion?

**Comment by untitaker** [comment]
I’ve generally seen that libraries do not export `Error` and rather just the enum that implements fail. Saves a heap allocation

**Comment by untitaker** [comment]
Fantastic, thanks! I just added you as crate maintainer to crates.io. Feel free to cut a new major version

**Pull request merged**
