### PR TITLE
Refactor a bit

### PR DESCRIPTION
**Pull request by gnuish**
Small refactoring.

Also possibly we can change `get_all()` to return Option instead of an empty slice and change the visibility of some functions but that's up to you.

Moving to only /src/ is to simplify a bit and pave the way if icalendar / vcard modules get added.

### CODE REVIEW

**Comment by untitaker** [comment]
Could you rebase? Thanks!

**Comment by gnuish** [comment]
Rebased

**Comment by untitaker** [comment]
Thanks!

**Comment by gnuish** [comment]
Just noticed that both versions of the fix got in :O. Between lines 385 and 386 should be `self.pos = start_pos;`

**Pull request merged**
